name = "gftp"
version = "1.0.0"
licenses = ["MIT"]
description = "A âœ¨ Gleam FTP/FTPS client library with full RFC support for both passive and active mode"
target = "erlang"
repository = { type = "github", user = "veeso", repo = "gftp" }
links = [{ title = "Codeberg", href = "https://codeberg.org/veeso/gftp" }]

[dependencies]
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"
gtempo = ">= 7.2.4 and < 8.0.0"
kafein = ">= 2.0.0 and < 3.0.0"
mug = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
